version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - nodejs2022q2-network
    volumes:
      - .:/app

  database:
    build:
      context: .
      dockerfile: database/dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - nodejs2022q2-network
    volumes:
      - nodejs2022q2-volume:/var/lib/postgresql/data

volumes:
  nodejs2022q2-volume:
    name: nodejs2022q2-volume

networks:
  nodejs2022q2-network:
    name: nodejs2022q2-network
    driver: bridge